# Generated by Django 4.2.13 on 2024-07-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_process_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="entry_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Time of product entry in process"
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="exit_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Time of product exit from process"
            ),
        ),
    ]
