# Generated by Django 4.2.14 on 2025-01-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_castingsnapshot_sand_temperature_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CastingSnapshot',
        ),
        migrations.DeleteModel(
            name='MoldingFloor',
        ),
        migrations.DeleteModel(
            name='RammingFloor',
        ),
    ]
