# Generated by Django 4.2.14 on 2025-01-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alter_moldingfloor_cope_heat_applied_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quality",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
