# Generated by Django 4.2.14 on 2025-01-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_quality_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
